recipes:
  custom_diamond_sword:
    material: DIAMOND_SWORD
    customModelData: 10006
    display_name: "Special Diamond Sword"
    lore:
      - "A mighty sword with unique powers."
    shape:
      - " DD"
      - " DD"
      - " S "
    ingredients:
      D: DIAMOND
      S: STICK
    commands:
      - "say {player} has crafted a Special Diamond Sword!"
      - "iagive {player} iaitemhere"
