name: FirstCraft
version: 1.0
main: org.unknowntehk.firstcraft.FirstCraftPlugin
api-version: 1.13
commands:
  recipes:
    description: Displays recipes GUI and manages plugin reload
    usage: /<command> [reload]
